# Application configuration
# Override hierarchy: settings.yaml -> ~/.cv-joint/settings.yaml -> settings.local.yaml

# Strings beginning with "~/" will undergo tilde expansion

data_dir: "./data"
markdown_root: "./markdown"

chat:
  model: "gpt-4o"
  temperature: 0.7

mcpServers:
  rag-knowledge: null # required for RAG functions

# Configure 'rag-knowledge' server in ~/.cv-joint/settings.yaml
#  or settings.local.yaml in this directory, e.g.:
#
# mcpServers:
#   rag-knowledge:
#     command: "~/.local/bin/uv"
#     args:
#       - "run"
#       - "--directory"
#       - "~/code/mcp-server-project"
#       - "python"
#       - "rag_knowledge_mcp.py"
#     env:
#       LOG_LEVEL: "INFO"
#     x-tool-name: "rag_search_knowledge"
